### ISSUE TITLE
improve active rendering

### ISSUE THREAD

**Issue by stes** [stes/Space-Warrior#39]
aim should be a framerate >= 60 FPS, better >= 100 FPS

**Comment by stes** [comment]
reached ~80 fps, remarkably more did not seem likely. therefore, fixed by ac5d8fbe61b61a5a3e886f826de249ec454d6f3e

**Comment by stes** [comment]
edit: in fact, even more fps ARE possible (max. ~220 fps). change the SWFrame.SLEEP_TIME constants to find a compromise between cpu usage and fps. see b3024ab2c21ab5c4ce2fca018124bbe173378cd2

**Comment by stes** [comment]
edit no. 2: 220 fps seems to be the absolute maximum; depending on your chipset, it is possible to only have ~60 fps (up to the mentioned 220 fps, maybe even more on a better pc than mine ;) )

**Comment by axblk** [comment]
up to 300 fps :D (1080p)
